<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-JJDSUCG" ignored="2" name="UPSRegressionTest" tests="3" failures="1" timestamp="2021-07-07T16:31:55 EDT" time="31.217" errors="0">
  <testcase name="mDemoTest2" time="0.015" classname="ups.pack.UPSTestRunner"/>
  <testcase name="signUpLinkTest" time="13.185" classname="ups.pack.UPSTestRunner"/>
  <testcase name="rediffMailAlertTest" time="6.94" classname="rediff.pack.ReddifTestRunner">
    <failure type="java.lang.AssertionError" message="expected [Please enter valid user name] but found [Please enter a valid user name]">
      <![CDATA[java.lang.AssertionError: expected [Please enter valid user name] but found [Please enter a valid user name]
at rediff.pack.ReddifTestRunner.rediffMailAlertTest(ReddifTestRunner.java:33)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- rediffMailAlertTest -->
  <testcase name="loginErrorMessageTest" time="0.0" classname="ups.pack.UPSTestRunner">
    <ignored/>
  </testcase> <!-- loginErrorMessageTest -->
  <testcase name="mDemoTest1" time="0.0" classname="ups.pack.UPSTestRunner">
    <ignored/>
  </testcase> <!-- mDemoTest1 -->
</testsuite> <!-- UPSRegressionTest -->
